#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

function main() {
  local version release_name

  while [ "${#}" != 0 ]; do
    case "${1}" in
      --version)
        version="${2}"
        shift 2
        ;;

      --release-name)
        release_name="${2}"
        shift 2
        ;;

      "")
        shift
        ;;

      *)
        echo "unknown argument \"${1}\""
        exit 1
    esac
  done

  # shellcheck disable=SC2086
  git config --global safe.directory '*'
  bosh -n create-release --final --version "$version" --name "$release_name" --tarball "releases/$release_name/$release_name-$version.tgz"
}

main "${@:-}"
