---
name: Test Pull Request

on:
  pull_request:
    branches:
    - main

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: stable
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run Unit Tests
      run: ./scripts/unit.sh
